name: rspec (Tests)
on: push

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: bundle install
      - name: rspec
        run: bundle exec rspec
