name: rspec (Tests)
on: push

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle install
      - name: rspec
        run: bundle exec rspec
